name: Publish Docker image to GHCR then update the image version on server

on: [push]

jobs:
  push_to_registry_and_deploy_to_server:
    if: github.ref == 'refs/heads/master'
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Github Container Registry with Docker
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull the previous version of the Docker image from Github Container Registry
        run: docker pull ghcr.io/axmouth/asp-drinks-mvc || true
      - name: Build the new version of the image
        run: docker build . --file asp.net-core-mvc-drink-shop/Dockerfile --tag ghcr.io/axmouth/asp-drinks-mvc --cache-from=ghcr.io/axmouth/asp-drinks-mvc
      #- name: Tag image
      #  run: docker tag ghcr.io/axmouth/asp-drinks-mvc latest
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Create empty .env file
        run: touch .env
      - name: Use docker-compose to deploy remotely
        env:
          CAPTCHA_SECRET: ${{ secrets.CAPTCHA_SECRET }}
          CAPTCHA_VERIFY_URL: https://hcaptcha.com/siteverify
          CONTACT_ADDRESS: ${{ secrets.CONTACT_ADDRESS }}
          CONTAINER_NAME: axmouth.dev-postfix
          ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_URL }}
          MAIL_FROM_ADDRESS: noreply@axmouth.dev
          MAIL_FROM_NAME: axmouth.dev
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          STATIC_FILE_DIR: /var/lib/axmouth/asp-drinks-mvc/static-assets
          WEBSITE_URL: asp-drinks-mvc.axmouth.dev
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: DOCKER_HOST="ssh://$SERVER_USERNAME@$SERVER_IP:$SSH_PORT" docker-compose up --remove-orphans -d
      - name: Push image to GHCR
        run: docker push ghcr.io/axmouth/asp-drinks-mvc || true
